Vagrant.configure("2") do |config|


config.vm.box = "hashicorp/precise64"
config.vm.provision "puppet"

config.vm.define "webserver" do |webserver|
webserver.vm.network "forwarded_port", guest: 80, host: 8080
webserver.vm.hostname = "webserver"
end

config.vm.define "appserver" do |appserver|
appserver.vm.hostname = "appserver"
end


end